### ISSUE TITLE
/view endpoint implementation

### ISSUE THREAD

**Issue by omarkmu** [Fox-Islam/krdict.js#2]
Are you already working on or do you intend to implement the https://krdict.korean.go.kr/api/view API? I was going to go ahead and start, but I thought it would be best to see if it's already in the works.

Also, I wanted to ask your thoughts about the inclusion of the 'explicitArray' option from xml2js; setting this to false would avoid all of the unnecessary one-item arrays in the result. This would also allow the output to match the expected API types. It would require a bit of an addition to the JSON cleaning step, namely ensuring that the "item", "meaning", and "translation" fields always have an array. This step could also convert the strings which are expected as integers, but that's not as pertinent. If the types match the expected API types, it would be possible to define a return type for dictionarySearch.

Regarding the cleaning step, I noticed an edge case issue in words containing the translation "sense" (such as 센스 or 눈치채다). Due to the replace, they are erroneously changed to "meaning". I assume this wouldn't be a problem for the keys containing underscores. This could be fixed by replacing "sense": instead, or iterating through the contents of the result object instead, which might be ideal if the conversions above were to be included.

Apologies if it's against GitHub etiquette to include different things in one issue like this. I can separate them into different issues if necessary, of course, I just wasn't sure which way would be proper and figured starting with one would be best.

**Comment by omarkmu** [comment]
I just realized I neglected to put a mention on this: @Fox-Islam

**Comment by Fox-Islam** [comment]
Oh! The TL;DR of this message I'm about to write is that I'm on board with all of these changes 😅 👍 

I wasn't aware of that endpoint but it looks like it's definitely worth adding to this!
Good catch on that cleaning step bug, you're right this should have the colon added to the regex pattern - I think all of them should to keep it consistent. I considered doing an iteration through the object keys initially but decided against it for simpler code, but if you think this could end up being a frequent issue then it may be worth doing

I think a good order to do these in would be:
- Fixing the "sense" bug
-> Making a patch version increase to to 1.4.1
- Adding the /view endpoint
-> Making a minor version increase to 1.5.0
- Changing the xml2js explicitArray option
-> Making a major version increase to 2.0.0

So far I've been considering this to be a very low-stakes project so I haven't been following semantic versioning 😬 But now is as good a time as any to start 

Unrelated to these changes I'd like to get a start on writing some tests for the repository. I'll hopefully get a moment to write some very simple test cases this weekend and open up a draft. If you're okay with how it's set out I think it should be merged before the sense bug fix and then have that case added as part of its commit? 
Though that's really dependent on how long it takes to write the few tests, it shouldn't be too long, the only issue is figuring out which test cases are worth adding at this stage

I really appreciate your insight, thanks for being a part of this repository!

**Comment by omarkmu** [comment]
Sounds good! Iterating in the cleaning step might be worth it, especially considering the view endpoint's response object has even more fields containing underscores. I think iteration would be more efficient if there are more keys to replace.

And no problem, thanks for creating it 😄

**Comment by omarkmu** [comment]
@Fox-Islam Hi, any updates on this? I can get started on the /view endpoint, but I thought you'd prefer making the patch version update first.

**Comment by Fox-Islam** [comment]
> @Fox-Islam Hi, any updates on this? I can get started on the /view endpoint, but I thought you'd prefer making the patch version update first.

 @omarkmu Ahh, sorry, this kind of fell to the wayside! Yes, absolutely, I'll take care of that now!

**Comment by omarkmu** [comment]
@Fox-Islam No worries, thanks for the quick response! Is it ready to go ahead with the implementation of the /view endpoint now?

**Comment by Fox-Islam** [comment]
@omarkmu Yep, it should be! Be sure to let me know if you have any questions or concerns!

**Comment by omarkmu** [comment]
@Fox-Islam Basic [implementation](https://github.com/omarkmu/krdict.js/commit/ed5148ed0546ddf7c03d58c185e7f1921de68f63) is all set, but a change I was hesitant to make was the addition of more key remaps. The /view endpoint returns a result with a few key names which are a bit odd, and more containing "sense" rather than "meaning". I figured it'd be best to check your preferences for what the renames should be. All of them are on the API reference page, of course.

Also, it just occurred to me: should I go ahead and create an incomplete pull request for further discussion and code review?

**Comment by Fox-Islam** [comment]
@omarkmu Ahh, wonderful, thank you! 
Oddly I can't reach the View API page because of (supposedly) an 020: unregistered key issue 🤔 
If you open up an incomplete PR I'd be happy to give it a look and discuss! My preference would be to rename them so that they at least make more sense than the properties they currently have, which, fortunately, isn't a very high bar 😅

**Comment by omarkmu** [comment]
@Fox-Islam No problem! I've opened up a draft pull request at #7.
